include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable/disable specific rules
    avoid_print: true
    always_declare_return_types: true
    prefer_final_locals: true
    prefer_double_quotes: true

analyzer:
  errors:
    # You can set specific rules to be warnings or errors
    avoid_print: warning
    unnecessary_string_escapes: error
