name: mockup
description: Mockup provides ready-to-use mock data, text, and number generators to speed up UI development, testing, and prototyping.
version: 1.0.1
homepage: https://github.com/rohitsinghorg/mockup

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: