name: mockup
description: A pure dart library that can enrich your standalone UI by acting as a data source
version: 0.0.1
homepage: https://github.com/rohitsinghorg/mockup

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: